/**
 * Temporary: clinics seed until CMS/API integration is wired.
 * Replace with a CMS client call in BookingService.
 */
import type { Clinic } from '@ns/types';

export const CLINICS_SEED: Clinic[] = [
  {
    id: 'urazova-chirurgia',
    name: { sk: 'Ambulancia úrazovej chirurgie', en: 'Trauma Surgery Clinic' },
    specialty: { sk: 'Úrazová chirurgia', en: 'Trauma surgery' },
    doctor: 'MUDr. Lukáš Harmaňoš',
    location: { sk: 'Prízemie', en: 'Ground floor' },
    phone: '057 / 7871 218',
    status: 'open',
    bookable: true,
    referral: false,
    bookingDays: [2, 4], // Tue, Thu
    schedule: { sk: ['Utorok & Štvrtok 09:00–14:00'], en: ['Tuesday & Thursday 09:00–14:00'] },
    bookingRule: { sk: 'Termíny len v utorok a štvrtok.', en: 'Appointments Tuesday & Thursday only.' },
  },
  {
    id: 'chirurgicka',
    name: { sk: 'Chirurgická ambulancia', en: 'General Surgery Clinic' },
    specialty: { sk: 'Všeobecná chirurgia', en: 'General surgery' },
    doctor: 'MUDr. Marek Andraščík',
    location: { sk: 'Prízemie', en: 'Ground floor' },
    phone: '057 / 7871 254',
    status: 'open',
    bookable: true,
    referral: false,
    bookingDays: [1, 2, 3, 4, 5],
    schedule: { sk: ['Pondelok–Piatok 07:00–15:00'], en: ['Monday–Friday 07:00–15:00'] },
    bookingRule: { sk: 'Štandardné objednávanie počas pracovných dní.', en: 'Standard booking on weekdays.' },
    fee: { sk: 'LSPP: 1,99 €', en: 'LSPP: €1.99' },
  },
  {
    id: 'urologicka',
    name: { sk: 'Urologická ambulancia', en: 'Urology Clinic' },
    specialty: { sk: 'Urológia', en: 'Urology' },
    doctor: 'MUDr. Patrik Nebesník',
    location: { sk: 'Budova polikliniky · 2. poschodie', en: 'Polyclinic building · 2nd floor' },
    phone: '057 / 7871 228',
    status: 'new',
    bookable: true,
    referral: true,
    acceptingNew: true,
    bookingDays: [1, 2, 3, 4, 5],
    schedule: { sk: ['Pondelok–Piatok 07:00–15:00'], en: ['Monday–Friday 07:00–15:00'] },
    bookingRule: { sk: 'Nová ambulancia, prijíma pacientov.', en: 'New clinic, accepting patients.' },
  },
  {
    id: 'angiologicka',
    name: { sk: 'Angiologická ambulancia', en: 'Angiology Clinic' },
    specialty: { sk: 'Angiológia', en: 'Angiology' },
    doctor: 'MUDr. Juraj Miko',
    location: { sk: 'Prízemie', en: 'Ground floor' },
    phone: '057 / 7871 285',
    status: 'new',
    bookable: true,
    referral: true,
    acceptingNew: true,
    bookingDays: [4, 5], // Thu, Fri
    bookingWindow: '13:00–14:00',
    schedule: { sk: ['Objednávanie Štv/Pia 13:00–14:00'], en: ['Booking Thu/Fri 13:00–14:00'] },
    bookingRule: { sk: 'Len Štv/Pia 13:00–14:00, výmenný lístok.', en: 'Thu/Fri 13:00–14:00 only, referral required.' },
  },
  {
    id: 'neurologicka',
    name: { sk: 'Neurologická ambulancia', en: 'Neurology Clinic' },
    specialty: { sk: 'Neurológia', en: 'Neurology' },
    doctor: 'MUDr. Kičik',
    location: { sk: 'Budova polikliniky', en: 'Polyclinic building' },
    status: 'alert',
    bookable: false,
    referral: true,
    schedule: { sk: ['Dočasný režim'], en: ['Temporary measures'] },
    bookingRule: { sk: 'Dočasný režim.', en: 'Temporary measures.' },
  },
  {
    id: 'hematologicka',
    name: { sk: 'Hematologická ambulancia', en: 'Hematology Clinic' },
    specialty: { sk: 'Hematológia', en: 'Hematology' },
    doctor: 'MUDr. Viera Coraničová',
    location: { sk: 'Budova Revital Plus', en: 'Revital Plus building' },
    phone: '057 / 7871 284',
    status: 'open',
    bookable: true,
    referral: true,
    bookingDays: [1, 2, 3, 4], // Mon–Thu
    schedule: { sk: ['Pondelok–Štvrtok 07:00–15:00'], en: ['Monday–Thursday 07:00–15:00'] },
    bookingRule: { sk: 'Piatok zatvorené, mimo hlavnej budovy.', en: 'Friday closed, outside main building.' },
  },
  {
    id: 'diabetologicka',
    name: { sk: 'Diabetologická ambulancia', en: 'Diabetology Clinic' },
    specialty: { sk: 'Diabetológia', en: 'Diabetology' },
    doctor: 'MUDr. Lenka Lajtarová',
    location: { sk: 'Areál nemocnice', en: 'Hospital complex' },
    status: 'closed',
    bookable: false,
    referral: true,
    schedule: { sk: ['Dočasne mimo prevádzky'], en: ['Temporarily closed'] },
    bookingRule: { sk: 'Objednávanie pozastavené.', en: 'Booking suspended.' },
  },
  {
    id: 'vnutorne-lekarstvo',
    name: { sk: 'Ambulancia vnútorného lekárstva', en: 'Internal Medicine Clinic' },
    specialty: { sk: 'Vnútorné lekárstvo', en: 'Internal medicine' },
    doctor: 'MUDr. Jana Borščová',
    location: { sk: 'Prízemie', en: 'Ground floor' },
    phone: '057 / 7871 285',
    status: 'open',
    bookable: true,
    referral: true,
    bookingDays: [1, 2, 3, 4, 5],
    schedule: { sk: ['Pondelok–Piatok 07:00–15:00'], en: ['Monday–Friday 07:00–15:00'] },
    bookingRule: { sk: 'Príjmová ambulancia.', en: 'Admission clinic.' },
  },
];
