/**
 * Temporary: clinics seed until CMS/API integration is wired.
 * Replace with a CMS client call in BookingService.
 */
import type { Clinic } from '@ns/types';

export const CLINICS_SEED: Clinic[] = [
  {
    id: 'urazova-chirurgia',
    name: { sk: 'Ambulancia úrazovej chirurgie', en: 'Trauma Surgery Clinic' },
    specialty: { sk: 'Úrazová chirurgia', en: 'Trauma surgery' },
    doctor: 'MUDr. Lukáš Harmaňoš',
    location: { sk: 'Prízemie', en: 'Ground floor' },
    phone: '057 / 7871 248',
    status: 'open',
    bookable: true,
    referral: false,
    bookingDays: [2, 4], // Tue, Thu
    schedule: { sk: ['Utorok & Štvrtok 09:00–14:00'], en: ['Tuesday & Thursday 09:00–14:00'] },
    bookingRule: { sk: 'Termíny len v utorok a štvrtok.', en: 'Appointments Tuesday & Thursday only.' },
  },
  {
    id: 'chirurgicka',
    name: { sk: 'Chirurgická ambulancia', en: 'General Surgery Clinic' },
    specialty: { sk: 'Všeobecná chirurgia', en: 'General surgery' },
    doctor: 'MUDr. Marek Andraščík, MUDr. Jakub Lakatoš',
    location: { sk: 'Prízemie', en: 'Ground floor' },
    phone: '057 / 7871 254',
    status: 'open',
    bookable: true,
    referral: false,
    bookingDays: [1, 2, 3, 4, 5],
    schedule: { sk: ['Pondelok–Piatok 07:00–15:00'], en: ['Monday–Friday 07:00–15:00'] },
    bookingRule: { sk: 'Štandardné objednávanie počas pracovných dní.', en: 'Standard booking on weekdays.' },
    fee: { sk: 'LSPP: 1,99 €', en: 'LSPP: €1.99' },
  },
  {
    id: 'urologicka',
    name: { sk: 'Urologická ambulancia', en: 'Urology Clinic' },
    specialty: { sk: 'Urológia', en: 'Urology' },
    doctor: 'MUDr. Patrik Nebesník',
    location: { sk: 'Budova polikliniky · 2. poschodie', en: 'Polyclinic building · 2nd floor' },
    phone: '057 / 7871 228',
    status: 'new',
    bookable: true,
    referral: true,
    acceptingNew: true,
    bookingDays: [1, 2, 3, 4, 5],
    schedule: { sk: ['Pondelok–Piatok 07:00–15:00'], en: ['Monday–Friday 07:00–15:00'] },
    bookingRule: { sk: 'Nová ambulancia, prijíma pacientov.', en: 'New clinic, accepting patients.' },
  },
  {
    id: 'angiologicka',
    name: { sk: 'Angiologická ambulancia', en: 'Angiology Clinic' },
    specialty: { sk: 'Angiológia', en: 'Angiology' },
    doctor: 'MUDr. Juraj Miko',
    location: { sk: 'Prízemie', en: 'Ground floor' },
    phone: '057 / 7871 285',
    status: 'new',
    bookable: true,
    referral: true,
    acceptingNew: true,
    bookingDays: [4, 5], // Thu, Fri
    bookingWindow: '13:00–14:30',
    schedule: { sk: ['Objednávanie Štv/Pia 13:00–14:30'], en: ['Booking Thu/Fri 13:00–14:30'] },
    bookingRule: { sk: 'Len Štv/Pia 13:00–14:30, výmenný lístok.', en: 'Thu/Fri 13:00–14:30 only, referral required.' },
    telehealth: true,
    telehealthWindow: '13:00–14:30',
    telehealthRule: { sk: 'Videokonzultácie Štv/Pia 13:00–14:30. Výmenný lístok.', en: 'Video consultations Thu/Fri 13:00–14:30. Referral required.' },
  },
  {
    id: 'neurologicka',
    name: { sk: 'Neurologická ambulancia', en: 'Neurology Clinic' },
    specialty: { sk: 'Neurológia', en: 'Neurology' },
    doctor: 'MUDr. Vladimír Kičik',
    location: { sk: 'Budova polikliniky', en: 'Polyclinic building' },
    phone: '057 / 7871 212',
    status: 'open',
    bookable: true,
    referral: true,
    bookingDays: [1, 2, 3, 4, 5],
    schedule: { sk: ['Pondelok 06:00–11:00', 'Utorok & Štvrtok 06:00–12:00 a 13:00–14:00', 'Streda & Piatok 06:00–11:00'], en: ['Monday 06:00–11:00', 'Tuesday & Thursday 06:00–12:00 and 13:00–14:00', 'Wednesday & Friday 06:00–11:00'] },
    bookingRule: { sk: 'Ambulancia je späť v štandardnej prevádzke.', en: 'The clinic has returned to standard operation.' },
  },
  {
    id: 'hematologicka',
    name: { sk: 'Hematologická ambulancia', en: 'Hematology Clinic' },
    specialty: { sk: 'Hematológia', en: 'Hematology' },
    doctor: 'MUDr. Viera Coraničová',
    location: { sk: 'Budova Revital Plus', en: 'Revital Plus building' },
    phone: '057 / 7871 610',
    status: 'open',
    bookable: true,
    referral: true,
    bookingDays: [1, 2, 3, 4], // Mon–Thu
    schedule: { sk: ['Pondelok–Štvrtok 07:00–15:00'], en: ['Monday–Thursday 07:00–15:00'] },
    bookingRule: { sk: 'Piatok zatvorené, mimo hlavnej budovy.', en: 'Friday closed, outside main building.' },
  },
  {
    id: 'diabetologicka',
    name: { sk: 'Ambulancia diabetológie a porúch látkovej výmeny', en: 'Diabetology & Metabolic Disorders Clinic' },
    specialty: { sk: 'Diabetológia', en: 'Diabetology' },
    doctor: 'MUDr. Lenka Lajtarová',
    location: { sk: 'Areál nemocnice', en: 'Hospital complex' },
    status: 'closed',
    bookable: false,
    referral: true,
    schedule: { sk: ['Dočasne mimo prevádzky'], en: ['Temporarily closed'] },
    bookingRule: { sk: 'Objednávanie pozastavené.', en: 'Booking suspended.' },
  },
  {
    id: 'vnutorne-lekarstvo',
    name: { sk: 'Ambulancia vnútorného lekárstva', en: 'Internal Medicine Clinic' },
    specialty: { sk: 'Vnútorné lekárstvo', en: 'Internal medicine' },
    doctor: 'MUDr. Jana Borščová',
    location: { sk: 'Prízemie', en: 'Ground floor' },
    phone: '057 / 7871 285',
    status: 'open',
    bookable: true,
    referral: true,
    bookingDays: [1, 2, 3, 4, 5],
    schedule: { sk: ['Pondelok–Piatok 07:00–15:00'], en: ['Monday–Friday 07:00–15:00'] },
    bookingRule: { sk: 'Príjmová ambulancia.', en: 'Admission clinic.' },
    telehealth: true,
    telehealthWindow: '09:00–11:00',
    telehealthRule: { sk: 'Videokonzultácie Po–Pia 09:00–11:00. Výmenný lístok.', en: 'Video consultations Mon–Fri 09:00–11:00. Referral required.' },
  },
  {
    id: 'fro-konzultacia',
    name: { sk: 'Rehabilitačná videokonzultácia (FRO)', en: 'Rehabilitation Video Consultation (FRO)' },
    specialty: { sk: 'Fyziatria a rehabilitácia', en: 'Physiatry & rehabilitation' },
    doctor: 'MUDr. Natália Kyjovská',
    location: { sk: 'Fyziatricko-rehabilitačné oddelenie', en: 'Physiatry & Rehabilitation Department' },
    phone: '057 / 7871 237',
    status: 'open',
    bookable: true,
    referral: false,
    bookingDays: [1, 3, 5], // Mon, Wed, Fri
    bookingWindow: '10:00–12:00',
    schedule: { sk: ['Videokonzultácie Po/Str/Pia 10:00–12:00'], en: ['Video consultations Mon/Wed/Fri 10:00–12:00'] },
    bookingRule: { sk: 'Videokonzultácie Po/Str/Pia 10:00–12:00. Bez výmenného lístka.', en: 'Video consultations Mon/Wed/Fri 10:00–12:00. No referral required.' },
    telehealth: true,
    telehealthWindow: '10:00–12:00',
    telehealthRule: { sk: 'Videokonzultácie Po/Str/Pia 10:00–12:00. Bez výmenného lístka.', en: 'Video consultations Mon/Wed/Fri 10:00–12:00. No referral required.' },
  },
  {
    id: 'ortopedicka',
    name: { sk: 'Ortopedická ambulancia', en: 'Orthopedics Clinic' },
    specialty: { sk: 'Ortopédia', en: 'Orthopedics' },
    doctor: '',
    location: { sk: 'Budova polikliniky', en: 'Polyclinic building' },
    status: 'closed',
    bookable: false,
    referral: true,
    schedule: { sk: ['Obsah sa pripravuje'], en: ['Content coming soon'] },
    bookingRule: { sk: 'Nová ambulancia — obsah sa pripravuje.', en: 'New clinic — content is being prepared.' },
  },
  {
    id: 'kardiologicka',
    name: { sk: 'Kardiologická ambulancia', en: 'Cardiology Clinic' },
    specialty: { sk: 'Kardiológia', en: 'Cardiology' },
    doctor: '',
    location: { sk: 'Budova polikliniky', en: 'Polyclinic building' },
    status: 'closed',
    bookable: false,
    referral: true,
    schedule: { sk: ['Obsah sa pripravuje'], en: ['Content coming soon'] },
    bookingRule: { sk: 'Nová ambulancia — obsah sa pripravuje.', en: 'New clinic — content is being prepared.' },
  },
];
