/**
 * Development-time seed data from the design handoff.
 * In production this module is replaced by CMS/API calls.
 * Import this only in server components.
 */
import type { Seed } from '@ns/types';

export const SEED: Seed = {
  hospital: {
    name: 'Nemocnica Snina, s.r.o.',
    tagline: { sk: 'Poliklinika a lôžková časť', en: 'Polyclinic & Inpatient Care' },
    address: 'Sládkovičova 300/3, 069 01 Snina',
    ico: '36 476 138',
    dic: '2020025684',
    phone: '+421 57 766 01 11',
    reception: '057 / 7871 200',
    pharmacy: '057 / 7871 232',
    emergency: '112',
    email: 'sekretariat@nemocnicasnina.sk',
    region: { sk: 'Spádová oblasť Snina a Prešovský kraj', en: 'Snina district & Prešov region' },
  },

  pages: {
    hero: {
      badge: {
        sk: 'Prijímame nových pacientov · Urológia & Angiológia',
        en: 'Accepting new patients · Urology & Angiology',
      },
      title: { sk: 'Moderná nemocnica pre náš región', en: 'A modern hospital for our region' },
      subtitle: {
        sk: 'Poskytujeme ústavnú a ambulantnú zdravotnú starostlivosť pre obyvateľov Sniny a okolia — s obnovenými oddeleniami, novou diagnostikou a centrálnou recepciou, ktorá vás prevedie celou návštevou.',
        en: 'We provide inpatient and outpatient care for the people of Snina and the surrounding district — with renovated wards, new diagnostics, and a central reception that guides you through every visit.',
      },
    },
    about: {
      title: { sk: 'O nemocnici', en: 'About the hospital' },
      body: {
        sk: 'Nemocnica Snina, s.r.o. je spoločnosť vo vlastníctve mesta Snina a tvorí dôležitý pilier zdravotnej starostlivosti pre okres Snina a širší Prešovský región.',
        en: 'Nemocnica Snina, s.r.o. is a company owned by the City of Snina and a vital pillar of healthcare for the Snina district and the wider Prešov region.',
      },
    },
    aps: {
      title: {
        sk: 'Ambulantná pohotovostná služba (APS)',
        en: 'Ambulatory Emergency Service (APS)',
      },
      note: {
        sk: 'Nemocnica je organizátorom APS pre dospelých aj deti v okrese Snina. Pri ohrození života vždy volajte 112.',
        en: 'The hospital organises the APS for adults and children in the Snina district. In a life-threatening emergency always call 112.',
      },
    },
  },

  departments: [
    {
      id: 'chirurgia',
      name: { sk: 'Chirurgicko-traumatologické oddelenie', en: 'Surgery & Traumatology' },
      short: { sk: 'Chirurgia a traumatológia', en: 'Surgery & Trauma' },
      lead: 'MUDr. Andrej Kulan',
      leadRole: { sk: 'Primár', en: 'Head of Department' },
      deputy: 'MUDr. Marek Andraščík',
      beds: 47,
      phone: '057 / 7871 218',
      email: 'chirurgia@nemocnicasnina.sk',
      featured: true,
      summary: {
        sk: 'Komplexná chirurgická a úrazová starostlivosť. V marci 2024 sme zaviedli nové laparoskopické a traumatologické metódy.',
        en: 'Comprehensive surgical and trauma care. In March 2024 we introduced new laparoscopic and trauma methodologies.',
      },
      desc: {
        sk: 'Spojené chirurgicko-traumatologické oddelenie je jedným z hlavných pilierov nemocnice.',
        en: 'The combined surgery & traumatology department is one of the hospital\'s primary pillars.',
      },
      facilities: {
        sk: ['Obnovené operačné sály', 'Septická a aseptická chirurgia', 'Miniinvazívna laparoskopia', 'Úrazová ambulancia'],
        en: ['Renovated operating theatres', 'Septic & aseptic surgery', 'Minimally-invasive laparoscopy', 'Trauma clinic'],
      },
      visiting: { sk: 'Denne 14:00 – 16:00 a 18:00 – 19:00', en: 'Daily 14:00 – 16:00 and 18:00 – 19:00' },
    },
    {
      id: 'interne',
      name: { sk: 'Interné oddelenie', en: 'Internal Medicine' },
      short: { sk: 'Interné', en: 'Internal Medicine' },
      lead: 'MUDr. Jana Borščová',
      leadRole: { sk: 'Primárka', en: 'Head of Department' },
      deputy: 'Mgr. Citrjaková',
      deputyRole: { sk: 'Vedúca sestra', en: 'Head Nurse' },
      beds: 57,
      phone: '057 / 7871 240',
      email: 'interne@nemocnicasnina.sk',
      featured: true,
      summary: {
        sk: 'Najväčšie oddelenie nemocnice so špecializovanou jednotkou intenzívnej starostlivosti (JIS).',
        en: "The hospital's largest department, with a dedicated Intensive Care Unit (JIS).",
      },
      desc: {
        sk: 'Interné oddelenie pokrýva širokú internú patológiu — od kardiopulmonálnych ochorení po metabolické stavy.',
        en: 'Internal Medicine covers broad internal pathology — from cardiopulmonary disease to metabolic conditions.',
      },
      facilities: {
        sk: ['Jednotka intenzívnej starostlivosti (JIS)', 'Štandardné lôžkové izby', 'Príjmová interná ambulancia', 'Kardiologická diagnostika'],
        en: ['Intensive Care Unit (JIS)', 'Standard ward beds', 'Internal admission clinic', 'Cardiology diagnostics'],
      },
      visiting: {
        sk: 'Denne 14:30 – 16:30 · JIS po dohode so službukonajúcim lekárom',
        en: 'Daily 14:30 – 16:30 · ICU by arrangement with the duty physician',
      },
    },
    {
      id: 'gynekologia',
      name: { sk: 'Gynekologicko-pôrodnícke oddelenie', en: 'Gynecology & Obstetrics' },
      short: { sk: 'Gynekológia a pôrodníctvo', en: 'Gynecology & Obstetrics' },
      lead: 'MUDr. František Pavlovčin',
      leadRole: { sk: 'Primár', en: 'Head of Department' },
      beds: 30,
      phone: '057 / 7871 231',
      email: 'gynekologia@nemocnicasnina.sk',
      delivery: '057 / 7871 279',
      featured: true,
      summary: {
        sk: 'Starostlivosť o ženu v každom veku a humanizované pôrodníctvo s možnosťou prítomnosti blízkej osoby.',
        en: 'Care for women at every age and humanised childbirth, with the option of a companion present.',
      },
      desc: {
        sk: 'Naše pôrodnícke oddelenie kladie dôraz na humanizovaný a bezpečný pôrod.',
        en: 'Our maternity department emphasises a humanised, safe birth.',
      },
      facilities: {
        sk: ['Moderné pôrodné sály', 'Prítomnosť blízkej osoby pri pôrode', 'Rooming-in s novorodencom', 'Stiahnuteľný pôrodný plán'],
        en: ['Modern delivery rooms', 'Companion present at birth', 'Rooming-in with the newborn', 'Downloadable birth plan'],
      },
      visiting: { sk: 'Denne 15:00 – 17:00 · oddelenie šestonedelia individuálne', en: 'Daily 15:00 – 17:00 · postnatal ward individually' },
    },
    {
      id: 'pediatria',
      name: { sk: 'Detské oddelenie', en: 'Pediatrics' },
      short: { sk: 'Pediatria', en: 'Pediatrics' },
      lead: 'MUDr. Miroslava Seňková, MBA',
      leadRole: { sk: 'Primárka', en: 'Head of Department' },
      beds: 15,
      phone: '057 / 7871 278',
      email: 'pediatria@nemocnicasnina.sk',
      featured: false,
      summary: {
        sk: 'Starostlivosť o deti od novorodencov po dorast, s možnosťou pobytu rodiča (rooming-in).',
        en: 'Care for children from newborns to adolescents, with the option for a parent to stay (rooming-in).',
      },
      desc: { sk: 'Detské oddelenie poskytuje diagnostiku a liečbu.', en: 'Pediatrics provides diagnosis and treatment.' },
      facilities: {
        sk: ['Rooming-in pre rodičov', 'Detská JIS-ka pre akútne stavy', 'Herňa a priestor pre deti', 'Spolupráca s neonatológiou'],
        en: ['Rooming-in for parents', 'Pediatric acute care beds', 'Playroom & child-friendly space', 'Neonatology cooperation'],
      },
      visiting: { sk: 'Rodičia neobmedzene pri rooming-in · ostatní 14:00 – 17:00', en: 'Parents unrestricted with rooming-in · others 14:00 – 17:00' },
    },
    {
      id: 'neonatologia',
      name: { sk: 'Novorodenecké oddelenie', en: 'Neonatal Unit' },
      short: { sk: 'Neonatológia', en: 'Neonatology' },
      lead: 'Tím neonatológie',
      leadRole: { sk: 'Ošetrujúci personál', en: 'Attending staff' },
      beds: 10,
      phone: '057 / 7871 279',
      featured: false,
      summary: {
        sk: 'Špecializovaná starostlivosť o novorodencov v úzkej spolupráci s pôrodníctvom.',
        en: 'Specialised care for newborns in close cooperation with obstetrics.',
      },
      desc: { sk: 'Novorodenecké oddelenie zabezpečuje starostlivosť.', en: 'The neonatal unit cares for newborns.' },
      facilities: {
        sk: ['Starostlivosť o fyziologického novorodenca', 'Resuscitačný kútik', 'Podpora dojčenia'],
        en: ['Physiological newborn care', 'Resuscitation corner', 'Breastfeeding support'],
      },
      visiting: { sk: 'V rámci oddelenia šestonedelia', en: 'Within the postnatal ward' },
    },
    {
      id: 'oaim',
      name: { sk: 'Oddelenie anestéziológie a intenzívnej medicíny (OAIM)', en: 'Anesthesiology & Intensive Care (OAIM)' },
      short: { sk: 'OAIM', en: 'OAIM' },
      lead: 'MUDr. Norbert Orinín',
      leadRole: { sk: 'Primár', en: 'Head of Department' },
      beds: 4,
      phone: '057 / 7871 242',
      featured: false,
      summary: {
        sk: 'Resuscitačná a intenzívna starostlivosť o najkritickejších pacientov a perioperačná anestézia.',
        en: 'Resuscitation and intensive care for the most critical patients, and perioperative anaesthesia.',
      },
      desc: { sk: 'OAIM zabezpečuje anestéziu pri operačných výkonoch.', en: 'The OAIM provides anaesthesia for surgical procedures.' },
      facilities: {
        sk: ['Resuscitačné lôžka', 'Perioperačná anestéziológia', 'Monitorovanie vitálnych funkcií'],
        en: ['Resuscitation beds', 'Perioperative anaesthesiology', 'Vital-sign monitoring'],
      },
      visiting: { sk: 'Iba po dohode so službukonajúcim lekárom', en: 'Only by arrangement with the duty physician' },
    },
    {
      id: 'fro',
      name: { sk: 'Fyziatricko-rehabilitačné oddelenie (FRO)', en: 'Physiatry & Rehabilitation (FRO)' },
      short: { sk: 'Rehabilitácia', en: 'Rehabilitation' },
      lead: 'MUDr. Natália Kyjovská',
      leadRole: { sk: 'Primárka', en: 'Head of Department' },
      beds: 0,
      phone: '057 / 7871 237',
      email: 'fro@nemocnicasnina.sk',
      featured: true,
      summary: {
        sk: 'Liečebná rehabilitácia, fyzikálna terapia a individuálny pohybový program. Možnosť online objednania.',
        en: 'Therapeutic rehabilitation, physical therapy and individual exercise programmes. Online booking available.',
      },
      desc: { sk: 'FRO poskytuje fyzikálnu liečbu.', en: 'The FRO provides physical therapy.' },
      facilities: {
        sk: ['Elektroliečba a magnetoterapia', 'Vodoliečba', 'Individuálny liečebný telocvik', 'Online objednávanie termínov'],
        en: ['Electrotherapy & magnetotherapy', 'Hydrotherapy', 'Individual therapeutic exercise', 'Online appointment booking'],
      },
      visiting: { sk: 'Ambulantná prevádzka — podľa objednania', en: 'Outpatient operation — by appointment' },
    },
  ],

  clinics: [
    {
      id: 'urazova-chirurgia',
      name: { sk: 'Ambulancia úrazovej chirurgie', en: 'Trauma Surgery Clinic' },
      specialty: { sk: 'Úrazová chirurgia', en: 'Trauma surgery' },
      doctor: 'MUDr. Lukáš Harmaňoš',
      nurse: 'Radoslava Pauliková',
      location: { sk: 'Prízemie · meracie miesto protetiky „Neoprot"', en: "Ground floor · 'Neoprot' prosthetics measuring point" },
      phone: '057 / 7871 218',
      status: 'open',
      bookable: true,
      referral: false,
      schedule: { sk: ['Utorok & Štvrtok 09:00 – 14:00', 'Protetika: Ut/Št 08:00 – 10:30'], en: ['Tuesday & Thursday 09:00 – 14:00', 'Prosthetics: Tue/Thu 08:00 – 10:30'] },
      bookingDays: [2, 4],
      bookingRule: { sk: 'Termíny len v utorok a štvrtok. Pondelok, streda a piatok sú zablokované.', en: 'Appointments Tuesday & Thursday only. Monday, Wednesday and Friday are blocked.' },
    },
    {
      id: 'chirurgicka',
      name: { sk: 'Chirurgická ambulancia', en: 'General Surgery Clinic' },
      specialty: { sk: 'Všeobecná chirurgia', en: 'General surgery' },
      doctor: 'MUDr. Marek Andraščík, MUDr. M. Brečka, MUDr. L. Alušík',
      location: { sk: 'Prízemie', en: 'Ground floor' },
      phone: '057 / 7871 254',
      status: 'open',
      bookable: true,
      referral: false,
      schedule: { sk: ['Pondelok – Piatok 07:00 – 15:00', 'Pohotovosť (APS): nepretržite 24/7'], en: ['Monday – Friday 07:00 – 15:00', 'Emergency (APS): continuous 24/7'] },
      bookingDays: [1, 2, 3, 4, 5],
      fee: { sk: 'Poplatok za pohotovostné použitie (LSPP): 1,99 €', en: 'Emergency-use fee (LSPP): €1.99' },
      bookingRule: { sk: 'Štandardné objednávanie počas pracovných dní. Akútne stavy ošetríme nepretržite cez APS.', en: 'Standard booking on weekdays. Acute cases treated continuously via APS.' },
    },
    {
      id: 'urologicka',
      name: { sk: 'Urologická ambulancia', en: 'Urology Clinic' },
      specialty: { sk: 'Urológia', en: 'Urology' },
      doctor: 'MUDr. Patrik Nebesník',
      nurse: 'M. Polačková',
      location: { sk: 'Budova polikliniky · 2. poschodie', en: 'Polyclinic building · 2nd floor' },
      phone: '057 / 7871 228',
      status: 'new',
      acceptingNew: true,
      bookable: true,
      referral: true,
      schedule: { sk: ['Pondelok – Piatok 07:00 – 15:00'], en: ['Monday – Friday 07:00 – 15:00'] },
      bookingDays: [1, 2, 3, 4, 5],
      opened: '2024-10-01',
      bookingRule: { sk: 'Nová ambulancia (otvorená 1. 10. 2024). Aktívne prijíma nových pacientov.', en: 'New clinic (opened 1 Oct 2024). Actively accepting new patients.' },
    },
    {
      id: 'angiologicka',
      name: { sk: 'Angiologická ambulancia', en: 'Angiology Clinic' },
      specialty: { sk: 'Angiológia (cievne ochorenia)', en: 'Angiology (vascular)' },
      doctor: 'MUDr. Juraj Miko',
      nurse: 'Bc. Edita Barnová',
      location: { sk: 'Prízemie · priestory interného oddelenia', en: 'Ground floor · internal medicine premises' },
      phone: '057 / 7871 285',
      status: 'new',
      acceptingNew: true,
      bookable: true,
      referral: true,
      schedule: { sk: ['Ordinačné hodiny: Po – Str 07:00 – 15:00', 'Objednávanie LEN Štv/Pia 13:00 – 14:00'], en: ['Clinic hours: Mon – Wed 07:00 – 15:00', 'Booking ONLY Thu/Fri 13:00 – 14:00'] },
      bookingDays: [4, 5],
      bookingWindow: '13:00–14:00',
      bookingRule: { sk: 'Objednať sa možno iba vo štvrtok a piatok medzi 13:00 – 14:00. Vyžaduje sa výmenný lístok.', en: 'Booking is possible only Thursday & Friday between 13:00 – 14:00. A referral (výmenný lístok) is required.' },
    },
    {
      id: 'neurologicka',
      name: { sk: 'Neurologická ambulancia', en: 'Neurology Clinic' },
      specialty: { sk: 'Neurológia', en: 'Neurology' },
      doctor: 'MUDr. Kičik',
      location: { sk: 'Budova polikliniky', en: 'Polyclinic building' },
      phone: '0918 088 183',
      status: 'alert',
      bookable: false,
      referral: true,
      schedule: { sk: ['Dočasný režim — kontaktujte na uvedenom čísle'], en: ['Temporary measures — contact on the number listed'] },
      bookingRule: { sk: 'Ambulancia funguje v dočasnom režime s náhradným kontaktom. Sledujte aktuálne oznamy.', en: 'The clinic operates under temporary measures with a substitute contact. Watch the announcements.' },
    },
    {
      id: 'hematologicka',
      name: { sk: 'Hematologická ambulancia', en: 'Hematology Clinic' },
      specialty: { sk: 'Hematológia', en: 'Hematology' },
      doctor: 'MUDr. Viera Coraničová',
      location: { sk: 'Budova Revital Plus · 1. poschodie (nad lekárňou)', en: 'Revital Plus building · 1st floor (above the pharmacy)' },
      phone: '057 / 7871 284',
      status: 'open',
      bookable: true,
      referral: true,
      schedule: { sk: ['Pondelok – Štvrtok 07:00 – 15:00', 'Piatok zatvorené'], en: ['Monday – Thursday 07:00 – 15:00', 'Friday closed'] },
      bookingDays: [1, 2, 3, 4],
      bookingRule: { sk: 'Pozor: ambulancia sídli mimo hlavnej budovy. Piatok je zatvorené.', en: 'Note: this clinic is located outside the main building. Closed on Friday.' },
    },
    {
      id: 'diabetologicka',
      name: { sk: 'Diabetologická ambulancia', en: 'Diabetology Clinic' },
      specialty: { sk: 'Diabetológia', en: 'Diabetology' },
      doctor: 'MUDr. Lenka Lajtarová',
      location: { sk: 'Areál nemocnice', en: 'Hospital complex' },
      status: 'closed',
      bookable: false,
      referral: true,
      schedule: { sk: ['Dočasne mimo prevádzky / obmedzená prevádzka'], en: ['Temporarily closed / limited operation'] },
      bookingRule: { sk: 'Ambulancia je dočasne mimo prevádzky — online objednávanie je pozastavené.', en: 'The clinic is temporarily closed — online booking is suspended.' },
    },
    {
      id: 'vnutorne-lekarstvo',
      name: { sk: 'Ambulancia vnútorného lekárstva', en: 'Internal Medicine Clinic' },
      specialty: { sk: 'Vnútorné lekárstvo', en: 'Internal medicine' },
      doctor: 'MUDr. Jana Borščová',
      location: { sk: 'Prízemie', en: 'Ground floor' },
      phone: '057 / 7871 285',
      status: 'open',
      bookable: true,
      referral: true,
      schedule: { sk: ['Príjmová ambulancia interného oddelenia', 'Pondelok – Piatok 07:00 – 15:00'], en: ['Admission clinic for Internal Medicine', 'Monday – Friday 07:00 – 15:00'] },
      bookingDays: [1, 2, 3, 4, 5],
      bookingRule: { sk: 'Príjmová ambulancia interného oddelenia.', en: 'Admission clinic for the Internal Medicine department.' },
    },
  ],

  physicians: [
    { id: 'kulan', name: 'MUDr. Andrej Kulan', role: { sk: 'Primár · Chirurgia a traumatológia', en: 'Head · Surgery & Traumatology' }, dept: 'chirurgia', langs: ['SK', 'EN'], accepting: false, bio: { sk: 'Primár chirurgicko-traumatologického oddelenia. Venuje sa všeobecnej a miniinvazívnej chirurgii.', en: 'Head of the surgery & traumatology department, focusing on general and minimally-invasive surgery.' } },
    { id: 'andrascik', name: 'MUDr. Marek Andraščík', role: { sk: 'Zástupca primára · Chirurgia', en: 'Deputy head · Surgery' }, dept: 'chirurgia', langs: ['SK'], accepting: false, bio: { sk: 'Zástupca primára, všeobecná a úrazová chirurgia.', en: 'Deputy head; general and trauma surgery.' } },
    { id: 'borscova', name: 'MUDr. Jana Borščová', role: { sk: 'Primárka · Interné oddelenie', en: 'Head · Internal Medicine' }, dept: 'interne', langs: ['SK', 'EN'], accepting: true, bio: { sk: 'Primárka interného oddelenia a vnútorného lekárstva.', en: 'Head of internal medicine and the internal admission clinic.' } },
    { id: 'pavlovcin', name: 'MUDr. František Pavlovčin', role: { sk: 'Primár · Gynekológia a pôrodníctvo', en: 'Head · Gynecology & Obstetrics' }, dept: 'gynekologia', langs: ['SK'], accepting: true, bio: { sk: 'Primár gynekologicko-pôrodníckeho oddelenia.', en: 'Head of the gynecology & obstetrics department.' } },
    { id: 'senkova', name: 'MUDr. Miroslava Seňková, MBA', role: { sk: 'Primárka · Detské oddelenie', en: 'Head · Pediatrics' }, dept: 'pediatria', langs: ['SK', 'EN'], accepting: true, bio: { sk: 'Primárka detského oddelenia.', en: 'Head of the pediatrics department.' } },
    { id: 'orinin', name: 'MUDr. Norbert Orinín', role: { sk: 'Primár · OAIM', en: 'Head · OAIM' }, dept: 'oaim', langs: ['SK'], accepting: false, bio: { sk: 'Primár oddelenia anestéziológie a intenzívnej medicíny.', en: 'Head of anesthesiology & intensive care.' } },
    { id: 'kyjovska', name: 'MUDr. Natália Kyjovská', role: { sk: 'Primárka · Rehabilitácia (FRO)', en: 'Head · Rehabilitation (FRO)' }, dept: 'fro', langs: ['SK'], accepting: true, bio: { sk: 'Primárka fyziatricko-rehabilitačného oddelenia.', en: 'Head of the physiatry & rehabilitation department.' } },
    { id: 'harmanos', name: 'MUDr. Lukáš Harmaňoš', role: { sk: 'Úrazová chirurgia', en: 'Trauma surgery' }, dept: 'chirurgia', clinic: 'urazova-chirurgia', langs: ['SK'], accepting: false, bio: { sk: 'Lekár úrazovej chirurgickej ambulancie.', en: 'Physician at the trauma surgery clinic.' } },
    { id: 'nebesnik', name: 'MUDr. Patrik Nebesník', role: { sk: 'Urológ', en: 'Urologist' }, clinic: 'urologicka', langs: ['SK', 'EN'], accepting: true, bio: { sk: 'Vedie novú urologickú ambulanciu, ktorá aktívne prijíma nových pacientov.', en: 'Leads the new urology clinic, which is actively accepting new patients.' } },
    { id: 'miko', name: 'MUDr. Juraj Miko', role: { sk: 'Angiológ', en: 'Angiologist' }, clinic: 'angiologicka', langs: ['SK'], accepting: true, bio: { sk: 'Angiológ — diagnostika a liečba cievnych ochorení. Vyžaduje sa výmenný lístok.', en: 'Angiologist — diagnosis and treatment of vascular disease. A referral is required.' } },
    { id: 'kicik', name: 'MUDr. Kičik', role: { sk: 'Neurológ', en: 'Neurologist' }, clinic: 'neurologicka', langs: ['SK'], accepting: false, bio: { sk: 'Neurologická ambulancia v dočasnom režime.', en: 'Neurology clinic operating under temporary measures.' } },
    { id: 'coranicova', name: 'MUDr. Viera Coraničová', role: { sk: 'Hematológia · Laboratórna medicína', en: 'Hematology · Laboratory Medicine' }, clinic: 'hematologicka', langs: ['SK'], accepting: true, bio: { sk: 'Vedie hematologickú ambulanciu a oddelenie laboratórnej medicíny.', en: 'Leads the hematology clinic and the department of laboratory medicine.' } },
    { id: 'lajtarova', name: 'MUDr. Lenka Lajtarová', role: { sk: 'Diabetológia', en: 'Diabetology' }, clinic: 'diabetologicka', langs: ['SK'], accepting: false, bio: { sk: 'Diabetologická ambulancia — dočasne mimo prevádzky.', en: 'Diabetology clinic — temporarily closed.' } },
    { id: 'lajtar', name: 'MUDr. Michal Lajtar', role: { sk: 'Rádiodiagnostika', en: 'Radiodiagnostics' }, facility: 'rdg', langs: ['SK'], accepting: false, bio: { sk: 'Vedie rádiodiagnostické oddelenie (CT, RTG, USG).', en: 'Leads the radiodiagnostic department (CT, X-ray, ultrasound).' } },
  ],

  services: [
    { id: 'laparoskopia', name: { sk: 'Miniinvazívna laparoskopia', en: 'Minimally-invasive laparoscopy' }, dept: 'chirurgia', icon: 'scalpel', desc: { sk: 'Nové laparoskopické metódy zavedené v marci 2024 — kratšia rekonvalescencia a menšie jazvy.', en: 'New laparoscopic methods introduced March 2024 — shorter recovery and smaller scars.' } },
    { id: 'porod', name: { sk: 'Humanizovaný pôrod', en: 'Humanised childbirth' }, dept: 'gynekologia', icon: 'heart', desc: { sk: 'Moderné pôrodné sály, prítomnosť blízkej osoby a starostlivosť o novorodenca pri matke.', en: 'Modern delivery rooms, a companion present, and newborn care beside the mother.' } },
    { id: 'rehab', name: { sk: 'Liečebná rehabilitácia', en: 'Therapeutic rehabilitation' }, dept: 'fro', icon: 'activity', desc: { sk: 'Fyzikálna terapia, elektroliečba, vodoliečba a individuálny liečebný telocvik.', en: 'Physical therapy, electrotherapy, hydrotherapy and individual exercise programmes.' } },
    { id: 'urologia', name: { sk: 'Urologická starostlivosť', en: 'Urological care' }, clinic: 'urologicka', icon: 'stethoscope', desc: { sk: 'Nová ambulancia prijímajúca pacientov — diagnostika a liečba ochorení močových ciest.', en: 'A new clinic accepting patients — diagnosis and treatment of urinary-tract conditions.' } },
    { id: 'angio', name: { sk: 'Cievna (angiologická) diagnostika', en: 'Vascular (angiology) diagnostics' }, clinic: 'angiologicka', icon: 'pulse', desc: { sk: 'Vyšetrenie a liečba cievnych ochorení. Vyžaduje sa výmenný lístok.', en: 'Examination and treatment of vascular disease. A referral is required.' } },
    { id: 'intenzivna', name: { sk: 'Intenzívna a resuscitačná starostlivosť', en: 'Intensive & resuscitation care' }, dept: 'oaim', icon: 'shield', desc: { sk: 'Resuscitačné lôžka OAIM a jednotka intenzívnej starostlivosti (JIS) interného oddelenia.', en: 'OAIM resuscitation beds and the Internal Medicine intensive care unit (JIS).' } },
    { id: 'lab', name: { sk: 'Laboratórna diagnostika', en: 'Laboratory diagnostics' }, facility: 'lab', icon: 'flask', desc: { sk: 'Klinická biochémia a hematológia s možnosťou stiahnutia výsledkov online.', en: 'Clinical biochemistry and hematology, with results downloadable online.' } },
    { id: 'zobrazovanie', name: { sk: 'Zobrazovacia diagnostika', en: 'Imaging diagnostics' }, facility: 'rdg', icon: 'scan', desc: { sk: 'CT, RTG a ultrazvuk (USG) s prípravou pre externých pacientov.', en: 'CT, X-ray and ultrasound (USG), with preparation guidance for external patients.' } },
  ],

  facilities: [
    { id: 'lab', name: { sk: 'Oddelenie laboratórnej medicíny', en: 'Department of Laboratory Medicine' }, lead: 'MUDr. Viera Coraničová', phone: '057 / 7871 284', kind: { sk: 'Klinická biochémia · Hematológia', en: 'Clinical biochemistry · Hematology' }, desc: { sk: 'Komplexná laboratórna diagnostika. Pacienti si môžu výsledky bezpečne stiahnuť online.', en: 'Comprehensive laboratory diagnostics. Patients can securely download results online.' }, features: { sk: ['Klinická biochémia', 'Hematológia', 'Bezpečné stiahnutie výsledkov (PDF)'], en: ['Clinical biochemistry', 'Hematology', 'Secure result download (PDF)'] } },
    { id: 'rdg', name: { sk: 'Rádiodiagnostické oddelenie', en: 'Radiodiagnostic Department' }, lead: 'MUDr. Michal Lajtar', phone: '057 / 7871 219', kind: { sk: 'CT · RTG · Ultrazvuk (USG)', en: 'CT · X-ray · Ultrasound (USG)' }, desc: { sk: 'Moderné zobrazovacie metódy.', en: 'Modern imaging methods.' }, features: { sk: ['Počítačová tomografia (CT)', 'RTG', 'Ultrazvuk (USG)', 'Pokyny pre externých pacientov'], en: ['Computed tomography (CT)', 'X-ray (RTG)', 'Ultrasound (USG)', 'Instructions for external patients'] } },
    { id: 'recepcia', name: { sk: 'Centrálna recepcia', en: 'Central Reception' }, phone: '057 / 7871 200', kind: { sk: 'Prvý kontakt · v prevádzke od 1. 9. 2024', en: 'First point of contact · operating since 1 Sep 2024' }, desc: { sk: 'Centrálna recepcia vás prevedie celou návštevou.', en: 'The central reception guides you through your whole visit.' }, features: { sk: ['Navigácia po areáli', 'Smerovanie na oddelenia', 'Informácie pre návštevy'], en: ['Campus navigation', 'Routing to departments', 'Visitor information'] } },
    { id: 'lekaren', name: { sk: 'Nemocničná lekáreň', en: 'Hospital Pharmacy' }, phone: '057 / 7871 232', kind: { sk: 'Výdaj liekov · v areáli nemocnice', en: 'Dispensing · within the hospital complex' }, desc: { sk: 'Lekáreň v areáli nemocnice s otváracími hodinami zosúladenými s ambulanciami.', en: 'A pharmacy within the hospital complex, with opening hours aligned to the clinics.' }, features: { sk: ['Výdaj na recept aj voľnopredajný', 'Hodiny zosúladené s ambulanciami'], en: ['Prescription & OTC dispensing', 'Hours aligned with clinics'] } },
  ],

  news: [
    { id: 'n-urologia', date: '2024-10-01', tag: { sk: 'Nová ambulancia', en: 'New clinic' }, type: 'good', title: { sk: 'Otvorili sme urologickú ambulanciu', en: 'Urology clinic now open' }, body: { sk: 'Od 1. októbra 2024 je v budove polikliniky v prevádzke nová urologická ambulancia pod vedením MUDr. Patrika Nebesníka. Ambulancia aktívne prijíma nových pacientov.', en: 'From 1 October 2024 a new urology clinic, led by MUDr. Patrik Nebesník, operates in the polyclinic building. The clinic is actively accepting new patients.' } },
    { id: 'n-recepcia', date: '2024-09-01', tag: { sk: 'Prevádzka', en: 'Operations' }, type: 'info', title: { sk: 'Spustili sme centrálnu recepciu', en: 'Central reception launched' }, body: { sk: 'Od 1. septembra 2024 funguje centrálna recepcia, ktorá pacientov nasmeruje a odbremení čakárne.', en: 'Since 1 September 2024 a central reception directs patients and relieves the waiting areas.' } },
    { id: 'n-angio', date: '2024-08-15', tag: { sk: 'Nová ambulancia', en: 'New clinic' }, type: 'good', title: { sk: 'Angiologická ambulancia rozširuje cievnu diagnostiku', en: 'Angiology clinic expands vascular diagnostics' }, body: { sk: 'Nová angiologická ambulancia rozširuje možnosti diagnostiky a liečby cievnych ochorení.', en: 'The new angiology clinic expands diagnosis and treatment of vascular disease.' } },
    { id: 'n-laparo', date: '2024-03-12', tag: { sk: 'Chirurgia', en: 'Surgery' }, type: 'good', title: { sk: 'Nové laparoskopické a traumatologické metódy', en: 'New laparoscopic & trauma methods' }, body: { sk: 'Chirurgicko-traumatologické oddelenie zaviedlo nové miniinvazívne laparoskopické a traumatologické postupy.', en: 'The surgery & traumatology department has introduced new minimally-invasive laparoscopic and trauma procedures.' } },
    { id: 'n-neuro', date: '2024-06-03', tag: { sk: 'Oznam', en: 'Notice' }, type: 'alert', title: { sk: 'Neurologická ambulancia — dočasný režim', en: 'Neurology clinic — temporary measures' }, body: { sk: 'Neurologická ambulancia funguje v dočasnom režime. Pacientov prosíme, aby využívali náhradný kontakt 0918 088 183.', en: 'The neurology clinic operates under temporary measures. Please use the substitute contact 0918 088 183.' } },
  ],

  disclosures: [
    { id: 'ZML-2024-051', type: { sk: 'Zmluva', en: 'Contract' }, partner: 'Siemens Healthineers — servis CT/MRI', value: '45 000 € / rok', date: '2024-09-20' },
    { id: 'FAK-2024-318', type: { sk: 'Faktúra', en: 'Invoice' }, partner: 'MedTech Medical Supplies, a.s.', value: '12 450,00 €', date: '2024-10-15' },
    { id: 'ZML-2024-047', type: { sk: 'Zmluva', en: 'Contract' }, partner: 'Východoslovenská energetika, a.s.', value: '—', date: '2024-08-01' },
    { id: 'FAK-2024-302', type: { sk: 'Faktúra', en: 'Invoice' }, partner: 'Slovak Energy Corp.', value: '8 200,00 €', date: '2024-10-10' },
    { id: 'ZML-2024-039', type: { sk: 'Zmluva', en: 'Contract' }, partner: 'Rekonštrukcia operačných sál — STAVON s.r.o.', value: '318 000,00 €', date: '2024-02-28' },
    { id: 'FAK-2024-281', type: { sk: 'Faktúra', en: 'Invoice' }, partner: 'B. Braun Medical s.r.o. — spotrebný materiál', value: '6 740,50 €', date: '2024-09-30' },
  ],
};
